import type { Product } from '@/types';

const d = (market: number): number => Math.round(market * 0.60 * 100) / 100;
const now = new Date().toISOString();

// All booster boxes sourced from cardboyz.com — prices reduced 30%
export const MOCK_PRODUCTS: Product[] = [

  // ─── POKÉMON ───────────────────────────────────────────────────────────────

  {
    id: 'poke-pokemon-day-2026-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: 'Pokémon Day 2026 Collection', set_code: 'PDC26',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/682045.jpg',
    release_date: '2026-02-27', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 55, our_price_usd: d(55),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-day-2026-collection-en',
    created_at: now, updated_at: now,
  },

  // ── ME04: Ninja Spinner (JP Mar 13) → Chaos Rising (EN May 22, 2026) ─────────
  {
    id: 'poke-me04-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Ninja Spinner', set_code: 'ME04-JP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/683774.jpg',
    release_date: '2026-03-13', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 292, our_price_usd: d(292),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-me04-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me04-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Chaos Rising', set_code: 'ME04',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/684444.jpg',
    release_date: '2026-05-22', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 351, our_price_usd: d(351),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-me04-en-box',
    created_at: now, updated_at: now,
  },

  // ── ME05: Abyss Eye (JP May 22) → Pitch Black (EN Jul 17, 2026) ────────────
  // Features Mega Darkrai ex, Mega Zeraora ex, Mega Chandelure ex, Mega Excadrill ex
  {
    id: 'poke-me05-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Abyss Eye', set_code: 'ME05-JP',
    image_url: 'https://archives.bulbagarden.net/media/upload/f/f8/ME5_Booster_Mega_Zeraora.png',
    release_date: '2026-05-22', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 278, our_price_usd: d(278),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-me05-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me05-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Pitch Black', set_code: 'ME05',
    image_url: 'https://archives.bulbagarden.net/media/upload/a/ae/ME5_Booster_Mega_Darkrai.png',
    release_date: '2026-07-17', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 351, our_price_usd: d(351),
    last_price_sync: now, is_pre_order: true, pack_count: 36,
    slug: 'pokemon-me05-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me05-en-etb',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Pitch Black', set_code: 'ME05',
    image_url: 'https://static0.srcdn.com/wordpress/wp-content/uploads/2026/04/pokemon-pitch-black-elite-trainer-box-and-cards.jpg',
    release_date: '2026-07-17', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 58, our_price_usd: d(58),
    last_price_sync: now, is_pre_order: true,
    slug: 'pokemon-me05-en-etb',
    created_at: now, updated_at: now,
  },
  // ── ME06: Storm Emeralda (JP Jul 31) → Storm Emerald (EN projected Oct 2026) ─
  // Features Mega Rayquaza ex. EN date not yet officially confirmed.
  {
    id: 'poke-me06-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Storm Emeralda', set_code: 'ME06-JP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/637384.jpg',
    release_date: '2026-07-31', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 285, our_price_usd: d(285),
    last_price_sync: now, is_pre_order: true, pack_count: 30,
    slug: 'pokemon-me06-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me06-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Storm Emerald', set_code: 'ME06',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/637384.jpg',
    release_date: '2026-10-03', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 365, our_price_usd: d(365),
    last_price_sync: now, is_pre_order: true, pack_count: 36,
    slug: 'pokemon-me06-en-box',
    created_at: now, updated_at: now,
  },

  {
    id: 'poke-me02-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Phantasmal Flames', set_code: 'SV09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/654137.jpg',
    release_date: '2025-05-23', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 449.99, our_price_usd: d(449.99),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-me02-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me03-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Perfect Order', set_code: 'ME03',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/672394.jpg',
    release_date: '2026-03-27', stock_quantity: 12, condition: 'sealed',
    market_price_usd: 299.95, our_price_usd: d(299.95),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-me03-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me01-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'ME Base Set', set_code: 'ME01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/644298.jpg',
    release_date: '2024-11-01', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 292, our_price_usd: d(292),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-me01-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv10-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Destined Rivals', set_code: 'SV10',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/624679.jpg',
    release_date: '2025-05-30', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 621, our_price_usd: d(621),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv10-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv9-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Journey Together', set_code: 'SV9',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/610931.jpg',
    release_date: '2025-03-28', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 292, our_price_usd: d(292),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv9-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv8-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Surging Sparks', set_code: 'SV8',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/565606.jpg',
    release_date: '2024-11-08', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 351, our_price_usd: d(351),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv8-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv7-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Stellar Crown', set_code: 'SV7',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/557354.jpg',
    release_date: '2024-09-13', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 365, our_price_usd: d(365),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv7-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv6-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Twilight Masquerade', set_code: 'SV6',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/543846.jpg',
    release_date: '2024-05-24', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 438, our_price_usd: d(438),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv6-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv5-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Temporal Forces', set_code: 'SV5',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/536225.jpg',
    release_date: '2024-03-22', stock_quantity: 15, condition: 'sealed',
    market_price_usd: 292, our_price_usd: d(292),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv5-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv4-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Paradox Rift', set_code: 'SV4',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/512821.jpg',
    release_date: '2023-11-03', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 329, our_price_usd: d(329),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-sv4-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-m2-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Inferno X', set_code: 'M2',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/655968.jpg',
    release_date: '2025-09-26', stock_quantity: 15, condition: 'sealed',
    market_price_usd: 180, our_price_usd: d(180),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-m2-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svbb-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Black Bolt', set_code: 'SV-BB',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/637384.jpg',
    release_date: '2025-02-07', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 199, our_price_usd: d(199),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-svbb-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv3a-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'Ruler of Black Flame', set_code: 'SV3a',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/565236.jpg',
    release_date: '2023-07-28', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 154, our_price_usd: d(154),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-sv3a-jp-box',
    created_at: now, updated_at: now,
  },

  // ── Pokémon Cases ──────────────────────────────────────────────────────────

  {
    id: 'poke-me02-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'ME Phantasmal Flames', set_code: 'SV09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/655281.jpg',
    release_date: '2025-05-23', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 2700, our_price_usd: d(2700),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-me02-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv10-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Destined Rivals', set_code: 'SV10',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/624679.jpg',
    release_date: '2025-05-30', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 3726, our_price_usd: d(3726),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv10-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv9-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Journey Together', set_code: 'SV9',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/614449.jpg',
    release_date: '2025-03-28', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 1752, our_price_usd: d(1752),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv9-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv8-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Surging Sparks', set_code: 'SV8',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/565606.jpg',
    release_date: '2024-11-08', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 2106, our_price_usd: d(2106),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv8-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-evs-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SWSH Evolving Skies', set_code: 'EVS',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/242436.jpg',
    release_date: '2021-08-27', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 12000, our_price_usd: d(12000),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-evs-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me04-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'ME Chaos Rising', set_code: 'ME04',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/684444.jpg',
    release_date: '2026-05-22', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 2106, our_price_usd: d(2106),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-me04-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me03-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'ME Perfect Order', set_code: 'ME03',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/672394.jpg',
    release_date: '2026-03-27', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 1800, our_price_usd: d(1800),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-me03-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me01-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'ME Base Set', set_code: 'ME01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/644298.jpg',
    release_date: '2024-11-01', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 1752, our_price_usd: d(1752),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-me01-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv7-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Stellar Crown', set_code: 'SV7',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/557354.jpg',
    release_date: '2024-09-13', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 2190, our_price_usd: d(2190),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv7-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv5-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Temporal Forces', set_code: 'SV5',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/536225.jpg',
    release_date: '2024-03-22', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 1752, our_price_usd: d(1752),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv5-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv4-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Paradox Rift', set_code: 'SV4',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/512821.jpg',
    release_date: '2023-11-03', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 1974, our_price_usd: d(1974),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv4-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv6-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Twilight Masquerade', set_code: 'SV6',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/543846.jpg',
    release_date: '2024-05-24', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 2628, our_price_usd: d(2628),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-sv6-en-case',
    created_at: now, updated_at: now,
  },

  // ─── POKÉMON SPECIAL SETS ─────────────────────────────────────────────────

  {
    id: 'poke-jungle-1st-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'Jungle 1st Edition', set_code: 'JU-1ED',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/107598.jpg',
    release_date: '1999-06-16', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 5000, our_price_usd: d(5000),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-jungle-1st-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-fossil-1st-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'Fossil 1st Edition', set_code: 'FO-1ED',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/107601.jpg',
    release_date: '1999-10-10', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 3200, our_price_usd: d(3200),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-fossil-1st-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-base-rev-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'Base Set Revised Unlimited', set_code: 'BS-REV',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/185731.jpg',
    release_date: '1999-01-09', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 3000, our_price_usd: d(3000),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-base-rev-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-champions-path-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: "Champion's Path", set_code: 'CHP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/218791.jpg',
    release_date: '2020-09-25', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 350, our_price_usd: d(350),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-champions-path-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-prismatic-evo-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'Prismatic Evolutions', set_code: 'PRE',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/593355.jpg',
    release_date: '2025-01-17', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 170, our_price_usd: d(170),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-prismatic-evo-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-hidden-fates-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'Hidden Fates', set_code: 'HIF',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/194729.jpg',
    release_date: '2019-08-23', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 170, our_price_usd: d(170),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-hidden-fates-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-shining-fates-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'Shining Fates', set_code: 'SHF',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/228821.jpg',
    release_date: '2021-02-19', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 142, our_price_usd: d(142),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-shining-fates-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-crown-zenith-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'Crown Zenith', set_code: 'CRZ',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/453470.jpg',
    release_date: '2023-01-20', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 122, our_price_usd: d(122),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-crown-zenith-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-paldean-fates-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'Paldean Fates', set_code: 'PAF',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/528040.jpg',
    release_date: '2024-01-26', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 260, our_price_usd: d(260),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-paldean-fates-etb-en',
    created_at: now, updated_at: now,
  },
  // ─── ONE PIECE (sorted by market price ↓) ────────────────────────────────

  // Cases
  {
    id: 'op-op11-jp-case',
    brand: 'onepiece', language: 'jp', product_type: 'case',
    set_name: 'A Fist of Divine Speed', set_code: 'OP11',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/620181.jpg',
    release_date: '2025-06-06', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 6132, our_price_usd: d(6132),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op11-jp-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op10-jp-case',
    brand: 'onepiece', language: 'jp', product_type: 'case',
    set_name: 'Royal Blood', set_code: 'OP10',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/586673.jpg',
    release_date: '2025-03-21', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 2760, our_price_usd: d(2760),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op10-jp-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op06-en-case',
    brand: 'onepiece', language: 'en', product_type: 'case',
    set_name: 'Wings of the Captain', set_code: 'OP06',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/515081.jpg',
    release_date: '2024-08-02', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 1500, our_price_usd: d(1500),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op06-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op13-en-case',
    brand: 'onepiece', language: 'en', product_type: 'case',
    set_name: 'Carrying on His Will', set_code: 'OP13',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op13/img_item01.webp',
    release_date: '2026-04-25', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 8400, our_price_usd: d(8400),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op13-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op09-en-case',
    brand: 'onepiece', language: 'en', product_type: 'case',
    set_name: 'Emperors in the New World', set_code: 'OP09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/563834.jpg',
    release_date: '2025-03-28', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 8160, our_price_usd: d(8160),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op09-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op07-en-case',
    brand: 'onepiece', language: 'en', product_type: 'case',
    set_name: '500 Years in the Future', set_code: 'OP07',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/532106.jpg',
    release_date: '2024-11-08', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 3960, our_price_usd: d(3960),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op07-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op13-jp-case',
    brand: 'onepiece', language: 'jp', product_type: 'case',
    set_name: 'Carrying on His Will', set_code: 'OP13',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op13/img_item01.webp',
    release_date: '2025-11-07', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 2328, our_price_usd: d(2328),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op13-jp-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op09-jp-case',
    brand: 'onepiece', language: 'jp', product_type: 'case',
    set_name: 'Emperors in the New World', set_code: 'OP09',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op09/mv_01.jpg',
    release_date: '2024-12-13', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 1848, our_price_usd: d(1848),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op09-jp-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op07-jp-case',
    brand: 'onepiece', language: 'jp', product_type: 'case',
    set_name: '500 Years in the Future', set_code: 'OP07',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op07/mv_01.jpg',
    release_date: '2024-06-28', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 1428, our_price_usd: d(1428),
    last_price_sync: now, is_pre_order: false, pack_count: 24, box_count: 12,
    slug: 'onepiece-op07-jp-case',
    created_at: now, updated_at: now,
  },

  // ── MTG Cases ───────────────────────────────────────────────────────────────

  {
    id: 'mtg-fin-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'Final Fantasy Play', set_code: 'FIN',
    image_url: 'https://media.wizards.com/2025/images/daily/en_ZcV8b56jf0.webp',
    release_date: '2025-06-13', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 1260, our_price_usd: d(1260),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-fin-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-tdr-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'Tarkir Dragonstorm', set_code: 'TDR',
    image_url: 'https://media.wizards.com/2025/images/daily/en_WZ4ZDjOLeP.webp',
    release_date: '2025-04-25', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 960, our_price_usd: d(960),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-tdr-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-spm-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'Spider-Man Play', set_code: 'SPM',
    image_url: 'https://media.wizards.com/2025/images/daily/en_EC9qVSPee7.png',
    release_date: '2025-09-26', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 960, our_price_usd: d(960),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-spm-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-tnt-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'TMNT Play', set_code: 'TNT',
    image_url: 'https://media.wizards.com/2025/images/daily/rJCJQBLkFD/en_Pj04YTRZxP.webp',
    release_date: '2026-03-06', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 1020, our_price_usd: d(1020),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-tnt-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fdn-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'Foundations Play', set_code: 'FDN',
    image_url: 'https://media.wizards.com/2024/images/daily/en_ewZYCzE0Ag.png',
    release_date: '2024-11-15', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 960, our_price_usd: d(960),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-fdn-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-ltr-en-case',
    brand: 'mtg', language: 'en', product_type: 'case',
    set_name: 'LotR: Tales of Middle-Earth Draft', set_code: 'LTR',
    image_url: 'https://media.wizards.com/2023/images/daily/en_gYnhHlInXX.png',
    release_date: '2023-06-23', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 2106, our_price_usd: d(2106),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'mtg-ltr-en-case',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fin-jp-case',
    brand: 'mtg', language: 'jp', product_type: 'case',
    set_name: 'Final Fantasy Collector JPN', set_code: 'FIN',
    image_url: 'https://media.wizards.com/2025/images/daily/en_A6mqWUmFzm.webp',
    release_date: '2025-06-13', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 4380, our_price_usd: d(4380),
    last_price_sync: now, is_pre_order: false, pack_count: 12, box_count: 6,
    slug: 'mtg-fin-jp-case',
    created_at: now, updated_at: now,
  },

  // ── White Flare / Black Bolt (SV11) ────────────────────────────────────────

  {
    id: 'poke-sv11w-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'SV White Flare', set_code: 'SV11W',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/637386.jpg',
    release_date: '2025-02-07', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 105, our_price_usd: d(105),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-sv11w-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv11w-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV White Flare', set_code: 'SV11W',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/630689.jpg',
    release_date: '2025-06-06', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 77, our_price_usd: d(77),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv11w-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv11b-jp-box',
    brand: 'pokemon', language: 'jp', product_type: 'booster_box',
    set_name: 'SV Black Bolt', set_code: 'SV11B',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/637384.jpg',
    release_date: '2025-02-07', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 100, our_price_usd: d(100),
    last_price_sync: now, is_pre_order: false, pack_count: 30,
    slug: 'pokemon-sv11b-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv11b-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Black Bolt', set_code: 'SV11B',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/630686.jpg',
    release_date: '2025-06-06', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 116, our_price_usd: d(116),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv11b-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Ascended Heroes (SV-AH) ───────────────────────────────────────

  {
    id: 'poke-svah-dc-en',
    brand: 'pokemon', language: 'en', product_type: 'display_case',
    set_name: 'SV Ascended Heroes', set_code: 'SV-AH',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/692362.jpg',
    release_date: '2025-10-17', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 82, our_price_usd: d(82),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svah-dc-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svah-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Ascended Heroes', set_code: 'SV-AH',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/668496.jpg',
    release_date: '2025-10-17', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 179, our_price_usd: d(179),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svah-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svah-pc-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: 'SV Ascended Heroes PC', set_code: 'SV-AH',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/668497.jpg',
    release_date: '2025-10-17', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 520, our_price_usd: d(520),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svah-pc-etb-en',
    created_at: now, updated_at: now,
  },

  {
    id: 'poke-svah-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SV Ascended Heroes', set_code: 'SV-AH',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/668496.jpg',
    release_date: '2025-10-17', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 220, our_price_usd: d(220),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-svah-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svah-en-case',
    brand: 'pokemon', language: 'en', product_type: 'case',
    set_name: 'SV Ascended Heroes', set_code: 'SV-AH',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/668496.jpg',
    release_date: '2025-10-17', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 1100, our_price_usd: d(1100),
    last_price_sync: now, is_pre_order: false, pack_count: 36, box_count: 6,
    slug: 'pokemon-svah-en-case',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: ME Phantasmal Flames (ME02) extras ────────────────────────────

  {
    id: 'poke-me02-upc-en',
    brand: 'pokemon', language: 'en', product_type: 'upc',
    set_name: 'ME Phantasmal Flames', set_code: 'SV09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/654213.jpg',
    release_date: '2025-05-23', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 275, our_price_usd: d(275),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me02-upc-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me02-cetb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Phantasmal Flames Center ETB', set_code: 'SV09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/654135.jpg',
    release_date: '2025-05-23', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 312, our_price_usd: d(312),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me02-cetb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me02-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Phantasmal Flames', set_code: 'SV09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/654136.jpg',
    release_date: '2025-05-23', stock_quantity: 9, condition: 'sealed',
    market_price_usd: 122, our_price_usd: d(122),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me02-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: ME Base Set (ME01) extras ─────────────────────────────────────

  {
    id: 'poke-me01-etb-gardevoir-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Mega Gardevoir ETB', set_code: 'ME01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/644279.jpg',
    release_date: '2024-11-01', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 77, our_price_usd: d(77),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me01-etb-gardevoir-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me01-etb-lucario-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Mega Lucario ETB', set_code: 'ME01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/648394.jpg',
    release_date: '2024-11-01', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 77, our_price_usd: d(77),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me01-etb-lucario-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Perfect Order (ME03) extras ───────────────────────────────────

  {
    id: 'poke-me03-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'ME Perfect Order', set_code: 'ME-PO',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/672401.jpg',
    release_date: '2025-03-14', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 72, our_price_usd: d(72),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me03-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-me03-pc-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: 'ME Perfect Order PC ETB', set_code: 'ME-PO',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/672404.jpg',
    release_date: '2025-03-14', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 136, our_price_usd: d(136),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-me03-pc-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Destined Rivals (SV10) extras ─────────────────────────────────

  {
    id: 'poke-sv10-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Destined Rivals', set_code: 'SV10',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/624676.jpg',
    release_date: '2025-05-30', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 176, our_price_usd: d(176),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv10-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Journey Together (SV9) extras ─────────────────────────────────

  {
    id: 'poke-sv9-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Journey Together', set_code: 'SV9',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/610930.jpg',
    release_date: '2025-03-28', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 117, our_price_usd: d(117),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv9-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Prismatic Evolutions (SVP) ────────────────────────────────────

  {
    id: 'poke-svp-spc-en',
    brand: 'pokemon', language: 'en', product_type: 'spc',
    set_name: 'SV Prismatic Evolutions', set_code: 'SVP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/622770.jpg',
    release_date: '2025-01-17', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 194, our_price_usd: d(194),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svp-spc-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svp-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Prismatic Evolutions', set_code: 'SVP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/593355.jpg',
    release_date: '2025-01-17', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 170, our_price_usd: d(170),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svp-etb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svp-surprise-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: 'SV Prismatic Evolutions Surprise Box', set_code: 'SVP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/593466.jpg',
    release_date: '2025-01-17', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 77, our_price_usd: d(77),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svp-surprise-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svp-lucario-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: "SV Prismatic Evolutions Sam's Club Lucario ex", set_code: 'SVP',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/648365.jpg',
    release_date: '2025-01-17', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 68, our_price_usd: d(68),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svp-lucario-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Blooming Waters (promo) ───────────────────────────────────────

  {
    id: 'poke-svbw-pc-en',
    brand: 'pokemon', language: 'en', product_type: 'premium_collection',
    set_name: 'SV Blooming Waters', set_code: 'SV-BW',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/609597.jpg',
    release_date: '2025-03-28', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 60, our_price_usd: d(60),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svbw-pc-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-svbw-poster-en',
    brand: 'pokemon', language: 'en', product_type: 'poster_collection',
    set_name: 'SV Blooming Waters Poster Collection', set_code: 'SV-BW',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/502001.jpg',
    release_date: '2025-03-28', stock_quantity: 9, condition: 'sealed',
    market_price_usd: 30, our_price_usd: d(30),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-svbw-poster-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Surging Sparks (SV8) extras ───────────────────────────────────


  // ── Pokémon: Scarlet & Violet 151 (SV3.5) ─────────────────────────────────

  {
    id: 'poke-sv3pt5-upc-en',
    brand: 'pokemon', language: 'en', product_type: 'upc',
    set_name: 'SV Pokémon 151', set_code: 'SV3.5',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/502005.jpg',
    release_date: '2023-09-22', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 875, our_price_usd: d(875),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv3pt5-upc-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv3pt5-cetb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Pokémon 151 Center ETB', set_code: 'SV3.5',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/501999.jpg',
    release_date: '2023-09-22', stock_quantity: 1, condition: 'sealed',
    market_price_usd: 868, our_price_usd: d(868),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv3pt5-cetb-en',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-sv3pt5-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SV Pokémon 151', set_code: 'SV3.5',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/503313.jpg',
    release_date: '2023-09-22', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 437, our_price_usd: d(437),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-sv3pt5-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Evolving Skies (SWSH7) ────────────────────────────────────────

  {
    id: 'poke-evs-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SWSH Evolving Skies', set_code: 'EVS',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/242436.jpg',
    release_date: '2021-08-27', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 285, our_price_usd: d(285),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-evs-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-evs-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SWSH Evolving Skies', set_code: 'EVS',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/242443.jpg',
    release_date: '2021-08-27', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 537, our_price_usd: d(537),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-evs-etb-en',
    created_at: now, updated_at: now,
  },

  // ── Pokémon: Fusion Strike (SWSH8) ─────────────────────────────────────────

  {
    id: 'poke-fst-en-box',
    brand: 'pokemon', language: 'en', product_type: 'booster_box',
    set_name: 'SWSH Fusion Strike', set_code: 'FST',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/247654.jpg',
    release_date: '2021-11-12', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 904, our_price_usd: d(904),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'pokemon-fst-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'poke-fst-etb-en',
    brand: 'pokemon', language: 'en', product_type: 'etb',
    set_name: 'SWSH Fusion Strike', set_code: 'FST',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/247671.jpg',
    release_date: '2021-11-12', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 88, our_price_usd: d(88),
    last_price_sync: now, is_pre_order: false,
    slug: 'pokemon-fst-etb-en',
    created_at: now, updated_at: now,
  },

  // ─── ONE PIECE (sorted by market price ↓) ────────────────────────────────
  // EN boxes command significantly higher prices than JP due to smaller print runs

  {
    id: 'op-op01-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Romance Dawn', set_code: 'OP01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/450086.jpg',
    release_date: '2023-07-08', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 1790, our_price_usd: d(1790),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op01-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op02-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Paramount War', set_code: 'OP02',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/455866.jpg',
    release_date: '2023-09-22', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 850, our_price_usd: d(850),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op02-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op03-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Pillars of Strength', set_code: 'OP03',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/477176.jpg',
    release_date: '2023-11-10', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 810, our_price_usd: d(810),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op03-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op13-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Carrying on His Will', set_code: 'OP13',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op13/img_item01.webp',
    release_date: '2026-04-25', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 700, our_price_usd: d(700),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op13-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op09-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Emperors in the New World', set_code: 'OP09',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/563834.jpg',
    release_date: '2025-03-28', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 680, our_price_usd: d(680),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op09-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op04-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Kingdoms of Intrigue', set_code: 'OP04',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/485833.jpg',
    release_date: '2024-02-23', stock_quantity: 12, condition: 'sealed',
    market_price_usd: 570, our_price_usd: d(570),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op04-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op11-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'A Fist of Divine Speed', set_code: 'OP11',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/620180.jpg',
    release_date: '2025-11-14', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 480, our_price_usd: d(480),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op11-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op06-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Wings of the Captain', set_code: 'OP06',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/515080.jpg',
    release_date: '2024-08-02', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 390, our_price_usd: d(390),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op06-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op07-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: '500 Years in the Future', set_code: 'OP07',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/532106.jpg',
    release_date: '2024-11-08', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 330, our_price_usd: d(330),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op07-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op14-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: "The Azure Sea's Seven", set_code: 'OP14',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op14/img_item01.webp',
    release_date: '2026-01-16', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 260, our_price_usd: d(260),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op14-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op10-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Royal Blood', set_code: 'OP10',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/586671.jpg',
    release_date: '2025-08-29', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 250, our_price_usd: d(250),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op10-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op12-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Legacy of the Master', set_code: 'OP12',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/628346.jpg',
    release_date: '2026-01-30', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 250, our_price_usd: d(250),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op12-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op08-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Two Legends', set_code: 'OP08',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/542504.jpg',
    release_date: '2025-01-31', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 250, our_price_usd: d(250),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op08-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op15-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: "Adventure on Kami's Island", set_code: 'OP15',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op15-eb04/img_item01.webp',
    release_date: '2026-04-03', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 210, our_price_usd: d(210),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op15-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op13-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: "Carrying on His Will", set_code: 'OP13',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op13/img_item01.webp',
    release_date: '2025-11-07', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 194, our_price_usd: d(194),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op13-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op11-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'A Fist of Divine Speed', set_code: 'OP11',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op11/mv_01.jpg',
    release_date: '2025-06-06', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 184, our_price_usd: d(184),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op11-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op09-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Emperors in the New World', set_code: 'OP09',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op09/mv_01.jpg',
    release_date: '2024-12-13', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 154, our_price_usd: d(154),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op09-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op06-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Wings of the Captain', set_code: 'OP06',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op06/mv_01.jpg',
    release_date: '2024-03-15', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 136, our_price_usd: d(136),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op06-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op05-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Awakening of the New Era', set_code: 'OP05',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op05/mv_01.jpg',
    release_date: '2023-12-08', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 122, our_price_usd: d(122),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op05-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op07-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: '500 Years in the Future', set_code: 'OP07',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op07/mv_01.jpg',
    release_date: '2024-06-28', stock_quantity: 12, condition: 'sealed',
    market_price_usd: 119, our_price_usd: d(119),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op07-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op05-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Awakening of the New Era', set_code: 'OP05',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/498734.jpg',
    release_date: '2024-05-24', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 110, our_price_usd: d(110),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op05-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op01-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Romance Dawn', set_code: 'OP01',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op01/mv_01.jpg',
    release_date: '2022-12-02', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 102, our_price_usd: d(102),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op01-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op12-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Legacy of the Master', set_code: 'OP12',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op12/mv_01.jpg',
    release_date: '2025-08-22', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 98, our_price_usd: d(98),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op12-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op14-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: "The Azure Sea's Seven", set_code: 'OP14',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op14/img_item01.webp',
    release_date: '2026-01-16', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 98, our_price_usd: d(98),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op14-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op02-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Paramount War', set_code: 'OP02',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op02/mv_01.jpg',
    release_date: '2023-03-10', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 95, our_price_usd: d(95),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op02-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op04-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Kingdoms of Intrigue', set_code: 'OP04',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op04/mv_01.jpg',
    release_date: '2023-09-22', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 95, our_price_usd: d(95),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op04-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op15-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: "Adventure on Kami's Island", set_code: 'OP15',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/op15-eb04/img_item01.webp',
    release_date: '2026-04-03', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 92, our_price_usd: d(92),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op15-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op10-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Royal Blood', set_code: 'OP10',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op10/mv_01.jpg',
    release_date: '2025-03-21', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 76, our_price_usd: d(76),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op10-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op08-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Two Legends', set_code: 'OP08',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op08/mv_01.jpg',
    release_date: '2024-09-13', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 74, our_price_usd: d(74),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op08-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-op03-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Pillars of Strength', set_code: 'OP03',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/op03/mv_01.jpg',
    release_date: '2023-06-30', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 69, our_price_usd: d(69),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-op03-jp-box',
    created_at: now, updated_at: now,
  },

  // ─── ONE PIECE: Extra Boosters (EB) ──────────────────────────────────────

  {
    id: 'op-eb02-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Anime 25th Collection', set_code: 'EB02',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/594069.jpg',
    release_date: '2025-01-17', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 650, our_price_usd: d(650),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb02-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-prb01-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'ONE PIECE CARD THE BEST', set_code: 'PRB01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/545399.jpg',
    release_date: '2025-04-04', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 900, our_price_usd: d(900),
    last_price_sync: now, is_pre_order: false, pack_count: 20,
    slug: 'onepiece-prb01-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb01-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Memorial Collection', set_code: 'EB01',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/521161.jpg',
    release_date: '2024-09-06', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 320, our_price_usd: d(320),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb01-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb03-en-box',
    brand: 'onepiece', language: 'en', product_type: 'booster_box',
    set_name: 'Heroines Edition', set_code: 'EB03',
    image_url: 'https://product-images.tcgplayer.com/fit-in/400x558/666891.jpg',
    release_date: '2026-01-31', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 300, our_price_usd: d(300),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb03-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb02-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Anime 25th Collection', set_code: 'EB02',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/eb02/mv_01.jpg',
    release_date: '2024-10-25', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 162, our_price_usd: d(162),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb02-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb01-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Memorial Collection', set_code: 'EB01',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/eb01/mv_01.jpg',
    release_date: '2023-12-22', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 138, our_price_usd: d(138),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb01-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-prb01-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'ONE PIECE CARD THE BEST', set_code: 'PRB01',
    image_url: 'https://en.onepiece-cardgame.com/images/products/boosters/prb01/mv_01.jpg',
    release_date: '2024-07-12', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 119, our_price_usd: d(119),
    last_price_sync: now, is_pre_order: false, pack_count: 20,
    slug: 'onepiece-prb01-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb03-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Heroines Edition', set_code: 'EB03',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/eb03/img_item01.webp',
    release_date: '2025-12-12', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 129, our_price_usd: d(129),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb03-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-prb02-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'ONE PIECE CARD THE BEST Vol.2', set_code: 'PRB02',
    image_url: 'https://en.onepiece-cardgame.com/renewal/images/products/boosters/prb02/img_item01.webp',
    release_date: '2025-12-19', stock_quantity: 5, condition: 'sealed',
    market_price_usd: 59, our_price_usd: d(59),
    last_price_sync: now, is_pre_order: false, pack_count: 20,
    slug: 'onepiece-prb02-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'op-eb04-jp-box',
    brand: 'onepiece', language: 'jp', product_type: 'booster_box',
    set_name: 'Egghead Crisis', set_code: 'EB04',
    image_url: 'https://jumpichiban.com/cdn/shop/files/One_Piece_Card_Game_-_Extra_Booster_EGGHEAD_CRISIS_EB-04_Box_or_Pack.png?v=1765267615&width=800',
    release_date: '2026-01-25', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 73, our_price_usd: d(73),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'onepiece-eb04-jp-box',
    created_at: now, updated_at: now,
  },

  // ─── MAGIC: THE GATHERING ──────────────────────────────────────────────────

  {
    id: 'mtg-tdr-en-collector',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Tarkir Dragonstorm Collector', set_code: 'TDR',
    image_url: 'https://media.wizards.com/2025/images/daily/en_WZ4ZDjOLeP.webp',
    release_date: '2025-04-25', stock_quantity: 2, condition: 'sealed',
    market_price_usd: 460, our_price_usd: d(460),
    last_price_sync: now, is_pre_order: false, pack_count: 12,
    slug: 'mtg-tdr-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fin-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Final Fantasy Play', set_code: 'FIN',
    image_url: 'https://media.wizards.com/2025/images/daily/en_ZcV8b56jf0.webp',
    release_date: '2025-06-13', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 210, our_price_usd: d(210),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-fin-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-spm-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Spider-Man Play', set_code: 'SPM',
    image_url: 'https://media.wizards.com/2025/images/daily/en_EC9qVSPee7.png',
    release_date: '2025-09-26', stock_quantity: 12, condition: 'sealed',
    market_price_usd: 160, our_price_usd: d(160),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-spm-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fdn-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Foundations Play', set_code: 'FDN',
    image_url: 'https://media.wizards.com/2024/images/daily/en_ewZYCzE0Ag.png',
    release_date: '2024-11-15', stock_quantity: 20, condition: 'sealed',
    market_price_usd: 160, our_price_usd: d(160),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-fdn-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-tnt-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'TMNT Play', set_code: 'TNT',
    image_url: 'https://media.wizards.com/2025/images/daily/rJCJQBLkFD/en_Pj04YTRZxP.webp',
    release_date: '2026-03-06', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 170, our_price_usd: d(170),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-tnt-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-atl-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Avatar ATLA Play', set_code: 'ATL',
    image_url: 'https://media.wizards.com/2025/images/daily/en_GGlVjEQHwR.webp',
    release_date: '2025-03-28', stock_quantity: 7, condition: 'sealed',
    market_price_usd: 140, our_price_usd: d(140),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-atl-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-lwe-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Lorwyn Eclipsed Play', set_code: 'LWE',
    image_url: 'https://media.wizards.com/2025/images/daily/en_YaHTKsL20v.webp',
    release_date: '2025-08-01', stock_quantity: 15, condition: 'sealed',
    market_price_usd: 140, our_price_usd: d(140),
    last_price_sync: now, is_pre_order: true, pack_count: 30,
    slug: 'mtg-lwe-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fdnj-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'Foundations Jumpstart', set_code: 'FDN-J',
    image_url: 'https://media.wizards.com/2024/images/daily/en_FWrkcSAS9A.png',
    release_date: '2024-11-15', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 110, our_price_usd: d(110),
    last_price_sync: now, is_pre_order: false, pack_count: 18,
    slug: 'mtg-fdnj-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-ltr-en-box',
    brand: 'mtg', language: 'en', product_type: 'booster_box',
    set_name: 'LotR: Tales of Middle-Earth Draft', set_code: 'LTR',
    image_url: 'https://media.wizards.com/2023/images/daily/en_gYnhHlInXX.png',
    release_date: '2023-06-23', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 351, our_price_usd: d(351),
    last_price_sync: now, is_pre_order: false, pack_count: 36,
    slug: 'mtg-ltr-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'mtg-fin-jp-collector',
    brand: 'mtg', language: 'jp', product_type: 'booster_box',
    set_name: 'Final Fantasy Collector JPN', set_code: 'FIN',
    image_url: 'https://media.wizards.com/2025/images/daily/en_A6mqWUmFzm.webp',
    release_date: '2025-06-13', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 730, our_price_usd: d(730),
    last_price_sync: now, is_pre_order: false, pack_count: 12,
    slug: 'mtg-fin-jp-box',
    created_at: now, updated_at: now,
  },

  // ─── YU-GI-OH! ─────────────────────────────────────────────────────────────

  {
    id: 'ygo-loch-jp-box',
    brand: 'yugioh', language: 'jp', product_type: 'booster_box',
    set_name: 'LOC The Heroes', set_code: 'LOC-H',
    image_url: 'https://img.yugioh-card.com/asia/wp-content/uploads/2026/01/cg2069_ED.png',
    release_date: '2025-01-24', stock_quantity: 6, condition: 'sealed',
    market_price_usd: 155, our_price_usd: d(155),
    last_price_sync: now, is_pre_order: false, pack_count: 15,
    slug: 'yugioh-loch-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-locr-jp-box',
    brand: 'yugioh', language: 'jp', product_type: 'booster_box',
    set_name: 'LOC The Rivals', set_code: 'LOC-R',
    image_url: 'https://img.yugioh-card.com/asia/wp-content/uploads/2026/01/cg2070_ED.png',
    release_date: '2026-03-20', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 130, our_price_usd: d(130),
    last_price_sync: now, is_pre_order: false, pack_count: 15,
    slug: 'yugioh-locr-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-blvo-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Blazing Dominion', set_code: 'BLVO',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2025/12/blzd_foil_550x550.png',
    release_date: '2024-09-19', stock_quantity: 25, condition: 'sealed',
    market_price_usd: 80, our_price_usd: d(80),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'yugioh-blvo-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-duad-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: "Duelist's Advance", set_code: 'DUAD',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2025/03/DUAD_550.png',
    release_date: '2024-11-08', stock_quantity: 0, condition: 'sealed',
    market_price_usd: 90, our_price_usd: d(90),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'yugioh-duad-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-ra05-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Rarity Collection V', set_code: 'RA05',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2025/12/ra05_foil_550x500.png',
    release_date: '2025-12-05', stock_quantity: 4, condition: 'sealed',
    market_price_usd: 120, our_price_usd: d(120),
    last_price_sync: now, is_pre_order: false, pack_count: 10,
    slug: 'yugioh-ra05-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-blgg-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Battles of Legend: Glorious Gallery', set_code: 'BLGG',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2026/02/BLGG_Foil_550-1.png',
    release_date: '2026-06-05', stock_quantity: 10, condition: 'sealed',
    market_price_usd: 85, our_price_usd: d(85),
    last_price_sync: now, is_pre_order: false, pack_count: 5,
    slug: 'yugioh-blgg-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-mzmu-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Maze of Muertos', set_code: 'MZMU',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2025/10/mzmu_3_foils_550x550.png',
    release_date: '2025-10-18', stock_quantity: 12, condition: 'sealed',
    market_price_usd: 75, our_price_usd: d(75),
    last_price_sync: now, is_pre_order: false, pack_count: 9,
    slug: 'yugioh-mzmu-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-cori-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Chaos Origins', set_code: 'CORI',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2026/03/CORI_550.png',
    release_date: '2026-03-21', stock_quantity: 8, condition: 'sealed',
    market_price_usd: 90, our_price_usd: d(90),
    last_price_sync: now, is_pre_order: false, pack_count: 9,
    slug: 'yugioh-cori-en-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-lochx-jp-box',
    brand: 'yugioh', language: 'jp', product_type: 'booster_box',
    set_name: 'LOC Heroes Enhanced', set_code: 'LOC-HX',
    image_url: 'https://img.yugioh-card.com/asia/wp-content/uploads/2026/01/cg2069_ED.png',
    release_date: '2026-02-28', stock_quantity: 3, condition: 'sealed',
    market_price_usd: 165, our_price_usd: d(165),
    last_price_sync: now, is_pre_order: false, pack_count: 15,
    slug: 'yugioh-lochx-jp-box',
    created_at: now, updated_at: now,
  },
  {
    id: 'ygo-tama-en-box',
    brand: 'yugioh', language: 'en', product_type: 'booster_box',
    set_name: 'Tactical Masters', set_code: 'TAMA',
    image_url: 'https://www.yugioh-card.com/en/wp-content/uploads/2025/03/DUAD_550.png',
    release_date: '2022-06-03', stock_quantity: 18, condition: 'sealed',
    market_price_usd: 70, our_price_usd: d(70),
    last_price_sync: now, is_pre_order: false, pack_count: 24,
    slug: 'yugioh-tama-en-box',
    created_at: now, updated_at: now,
  },
];

export function getMockProducts(filters: {
  brand?: string; language?: string; product_type?: string;
  in_stock_only?: boolean; pre_order?: boolean; sort_by?: string;
} = {}): Product[] {
  let list = [...MOCK_PRODUCTS];
  if (filters.brand)         list = list.filter(p => p.brand         === filters.brand);
  if (filters.language)      list = list.filter(p => p.language      === filters.language);
  if (filters.product_type)  list = list.filter(p => p.product_type  === filters.product_type);
  if (filters.in_stock_only) list = list.filter(p => p.stock_quantity > 0);
  if (filters.pre_order !== undefined) list = list.filter(p => p.is_pre_order === filters.pre_order);
  switch (filters.sort_by) {
    case 'price_asc':    list.sort((a, b) => a.our_price_usd  - b.our_price_usd);  break;
    case 'price_desc':   list.sort((a, b) => b.our_price_usd  - a.our_price_usd);  break;
    case 'release_date': list.sort((a, b) => b.release_date.localeCompare(a.release_date)); break;
  }
  return list;
}
